/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'beranda': RouteRecordInfo<'beranda', '/beranda', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'master-data-coa': RouteRecordInfo<'master-data-coa', '/master-data/coa', Record<never, never>, Record<never, never>>,
    'master-data-mapping': RouteRecordInfo<'master-data-mapping', '/master-data/mapping', Record<never, never>, Record<never, never>>,
    'master-data-unit': RouteRecordInfo<'master-data-unit', '/master-data/unit', Record<never, never>, Record<never, never>>,
    'not-authorized': RouteRecordInfo<'not-authorized', '/not-authorized', Record<never, never>, Record<never, never>>,
    'pengaturan-akun': RouteRecordInfo<'pengaturan-akun', '/pengaturan/akun', Record<never, never>, Record<never, never>>,
    'pengaturan-role': RouteRecordInfo<'pengaturan-role', '/pengaturan/role', Record<never, never>, Record<never, never>>,
    'transaksi-eleminasi': RouteRecordInfo<'transaksi-eleminasi', '/transaksi/eleminasi', Record<never, never>, Record<never, never>>,
    'transaksi-laporan': RouteRecordInfo<'transaksi-laporan', '/transaksi/laporan', Record<never, never>, Record<never, never>>,
    'transaksi-laporan-konsolidasi': RouteRecordInfo<'transaksi-laporan-konsolidasi', '/transaksi/laporan-konsolidasi', Record<never, never>, Record<never, never>>,
    'transaksi-upload-laporan': RouteRecordInfo<'transaksi-upload-laporan', '/transaksi/upload-laporan', Record<never, never>, Record<never, never>>,
  }
}
